config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :dashboard, only: :show
  resource :subscriptions, only: :create

  # Used to the redirect user to the current workbench
  # See CHOUETTE-797
  namespace :redirect do
    resources :lines, only: :show
    resources :companies, only: :show
    resources :stop_areas, only: :show
  end

  resources :workbenches, only: %i[show] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    resources :api_keys

    resources :autocomplete, only: [] do
      get :lines, on: :collection, defaults: { format: 'json' }
      get :companies, on: :collection, defaults: { format: 'json' }
      get :line_providers, on: :collection, defaults: { format: 'json' }
      get :line_notices, on: :collection, defaults: { format: 'json' }
      get :stop_areas, on: :collection, defaults: { format: 'json' }
      get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
      get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      get :users, on: :collection, defaults: { format: 'json' }
      get :macro_lists, on: :collection, defaults: { format: 'json' }
      get :control_lists, on: :collection, defaults: { format: 'json' }
      get :calendars, on: :collection, defaults: { format: 'json' }
    end

    resource :output, controller: :workbench_outputs
    resources :merges do
      member do
        put :rollback
      end
      collection do
        get :available_referentials
      end
    end

    delete :referentials, on: :member, action: :delete_referentials
    resources :referentials do # rubocop:disable Metrics/BlockLength
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :autocomplete, controller: 'referential_autocomplete', only: [] do
        defaults format: :json do
          collection do
            get :companies
            get :lines
            get :journey_patterns
            get :time_tables
            get :vehicle_journeys
          end
        end
      end

      member do
        put :archive
        put :unarchive
        get :journey_patterns
      end

      resources :autocomplete, only: [] do
        get :line_providers, on: :collection, defaults: { format: 'json' }
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end

      resources :lines, controller: 'referential_lines', only: %i[show] do # rubocop:disable Metrics/BlockLength
        resources :footnotes do
          collection do
            get 'edit_all'
            patch 'update_all'
          end
        end

        resources :routes do # rubocop:disable Metrics/BlockLength
          member do
            get 'edit_boarding_alighting'
            put 'save_boarding_alighting'
            post 'duplicate', to: 'routes#duplicate'
            get 'retrieve_nearby_stop_areas'
            get 'autocomplete_stop_areas'
          end
          collection do
            get 'fetch_opposite_routes'
            get 'fetch_user_permissions'
          end
          resource :journey_patterns, only: %i[show update], controller: :journey_patterns_collections
          resources :journey_patterns, only: [] do
            member do
              get 'available_specific_stop_places'
              put 'unassociate_shape'
              put 'duplicate'
            end

            resource :shapes, except: :index, module: 'journey_pattern' do
              collection do
                defaults format: :json do
                  get :get_user_permissions
                  put :update_line
                end
              end
            end
          end
        end
        resources :routing_constraint_zones
      end

      resources :routes, only: [] do
        resource :vehicle_journeys, only: %i[show update], controller: :route_vehicle_journeys
      end

      resources :vehicle_journeys, controller: 'referential_vehicle_journeys', only: [:index]

      resources :time_tables do
        member do
          post 'actualize'
          get 'duplicate'
          get 'month', defaults: { format: :json }
        end
      end
      resources :clean_ups

      scope module: 'redirect', only: :show do
        resources :routes
        resources :journey_patterns
        resources :vehicle_journeys
      end

      resources :service_counts, only: %i[index]
    end

    resources :notification_rules
    resources :macro_lists do
      resources :macro_list_runs, only: %w[new create]
    end

    resources :sources do
      post :retrieve, on: :member
    end

    concern :macro_runs do
      resources :macro_runs, only: [] do
        resources :macro_messages, only: :index
      end
    end

    resources :macro_list_runs, only: %w[new create show index], concerns: :macro_runs do
      resources :macro_context_runs, only: [], concerns: :macro_runs
    end

    resources :control_lists do
      resources :control_list_runs, only: %w[new create]
    end

    concern :control_runs do
      resources :control_runs, only: [] do
        resources :control_messages, only: :index
      end
    end

    resources :control_list_runs, only: %w[new create show index], concerns: :control_runs do
      resources :control_context_runs, only: [], concerns: :control_runs
    end

    resource :stop_area_referential, only: %i[show edit update] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :stop_area_routing_constraints
      resources :entrances
      resources :stop_area_groups

      resources :stop_area_providers

      resources :stop_areas do
        get :autocomplete, on: :collection
        get :fetch_connection_links, on: :member, defaults: { format: 'geojson' }

        resources :document_memberships, only: %i[index create destroy], controller: :stop_area_document_memberships
      end

      resources :autocomplete, only: [] do
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end
      resources :connection_links do
        get :get_connection_speeds, on: :collection, defaults: { format: 'json' }
      end
    end

    resource :line_referential, only: %i[show] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
      resources :line_routing_constraint_zones
      resources :line_groups

      resources :line_providers

      resources :lines do
        get :autocomplete, on: :collection

        resources :line_notice_memberships, only: %i[index new create destroy]
        get 'line_notice_memberships/edit', to: 'line_notice_memberships_collections#edit'
        patch 'line_notice_memberships', to: 'line_notice_memberships_collections#update'

        resources :document_memberships, only: %i[index create destroy], controller: :line_document_memberships
      end

      resources :companies do
        get :autocomplete, on: :collection

        resources :document_memberships, only: %i[index create destroy], controller: :company_document_memberships
      end

      resources :networks
      resources :line_notices
      resources :booking_arrangements
    end

    resource :shape_referential, only: [] do
      resources :shapes, except: [:create]
      resources :point_of_interests
      resources :point_of_interest_categories
      resources :service_facility_sets

      resources :accessibility_assessments do
        get :autocomplete, on: :collection
      end
    end

    resources :contracts

    resources :sequences

    resources :documents do
      get :download, on: :member
    end

    resources :document_providers

    resources :fare_zones
    resources :fare_providers

    resources :processing_rules, as: 'processing_rule_workbenches'

    resources :calendars do
      member do
        get 'month', defaults: { format: :json }
      end
    end

    resources :imports do
      get :download, on: :member
      get :internal_download, on: :member
    end

    get 'imports/:id/import_resources/:import_resource_id/messages',
        to: 'imports#messages',
        as: 'import_import_resource_import_messages'

    resources :exports do
      get :download, on: :member
    end
  end

  resource :workbench_confirmation, only: %i[new create]

  resources :workgroups, except: [:destroy] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    put :setup_deletion, on: :member
    put :remove_deletion, on: :member

    member do
      get :edit_aggregate
      get :edit_merge
    end

    resources :code_spaces, except: :destroy

    resources :document_types
    resources :processing_rules, as: 'processing_rule_workgroups', controller: 'workgroup_processing_rules'

    resources :workbenches, controller: :workgroup_workbenches, only: %i[new create show edit update] do
      resources :sharings, controller: 'workbench/sharings', only: %i[new create show destroy]
    end

    resource :output, controller: :workgroup_outputs
    resources :aggregates do
      member do
        put :rollback
      end
    end

    resources :publication_setups do
      resources :publications, only: [:create, :show]
    end

    resources :publication_apis do
      resources :publication_api_keys
    end

    resources :control_list_runs, controller: :workgroup_control_list_runs, only: %w[show index] do
      resources :control_runs, only: [] do

app/helpers/time_tables_helper.rb
require 'date'

module TimeTablesHelper

  def month_periode_enum(bounding_dates, years)
    if bounding_dates.empty?
      start_date = Date.today - years.years
      end_date = Date.today + years.years
    else
      start_date = (bounding_dates.min > Date.today ? Date.today : bounding_dates.min) - years.years
      end_date   = (bounding_dates.max < Date.today ? Date.today : bounding_dates.max) + years.years
    end
    
    (start_date..end_date).map(&:beginning_of_month).uniq.map(&:to_s)
  end

  def new_alt_calendar(options = {}, &block)
    raise(ArgumentError, "No year given")  unless options.has_key?(:year)
    raise(ArgumentError, "No month given") unless options.has_key?(:month)

    block                        ||= Proc.new {|d| nil}

    month_names = (!defined?(I18n) || I18n.t("date.month_names").include?("missing")) ? Date::MONTHNAMES.dup : I18n.t("date.month_names")

    defaults = {
      :table_id            => "calendar-#{options[:year]}-#{"%02d" % options[:month]}",
      :table_class         => 'calendar',
      :month_name_class    => 'monthName',
      :other_month_class   => 'outsideMonth',
      :day_name_class      => 'dayName',
      :day_class           => 'day',
      :abbrev              => false,
      :first_day_of_week   => 0,
      :accessible          => false,
      :show_today          => true,
      :previous_month_text => nil,
      :next_month_text     => nil,
      :month_header        => true,
      :calendar_title      => month_names[options[:month]],
      :summary             => "Calendrier pour #{month_names[options[:month]]} #{options[:year]}"
    }
    options = defaults.merge options

    first = Date.civil(options[:year], options[:month], 1)
    last = Date.civil(options[:year], options[:month], -1)

    first_weekday = first_day_of_week(options[:first_day_of_week])
    last_weekday = last_day_of_week(options[:first_day_of_week])

    day_names = (!defined?(I18n) || I18n.t("date.day_names").include?("missing")) ? Date::DAYNAMES : I18n.t("date.day_names")
    abbr_day_names = (!defined?(I18n) || I18n.t("date.abbr_day_names").include?("missing")) ? Date::ABBR_DAYNAMES : I18n.t("date.abbr_day_names")
    week_days = (0..6).to_a
    first_weekday.times do
      week_days.push(week_days.shift)
    end

    # TODO Use some kind of builder instead of straight HTML
    cal = %(<table id="#{options[:table_id]}" class="#{options[:table_class]}" border="0" cellspacing="0" cellpadding="0" summary="#{options[:summary]}">)
    cal << %(<thead>)

    if (options[:month_header])
      cal << %(<tr>)
      cal << %(<th class='weekNumber' scope="col"></th>)
      if options[:previous_month_text] or options[:next_month_text]
        cal << %(<th colspan="2">#{options[:previous_month_text]}</th>)
        colspan=3
      else
        colspan=7
      end
      cal << %(<th colspan="#{colspan}" class="#{options[:month_name_class]}">#{options[:calendar_title]}</th>)
      cal << %(<th colspan="2">#{options[:next_month_text]}</th>) if options[:next_month_text]
      cal << %(</tr>)
    end

    cal << %(<tr class="#{options[:day_name_class]}">)
    cal << %(<th class='weekNumber' scope="col"></th>)

    week_days.each do |wday|
      cal << %(<th id="#{th_id(Date::DAYNAMES[wday], options[:table_id])}" scope="col">)
      cal << (options[:abbrev] ? %(<abbr title="#{day_names[wday]}">#{t("calendars.days.#{Date::DAYNAMES[wday].downcase}")}</abbr>) : t("calendars.days.#{Date::DAYNAMES[wday].downcase}"))
      cal << %(</th>)
    end

    cal << "</tr></thead><tbody><tr>"

    # previous month
    beginning_of_week(first, first_weekday).upto(first - 1) do |d|
      cal << "<td class='weekNumber'>S#{d.strftime("%W").to_s}</td>" if d.wday == first_weekday
      cal << generate_other_month_cell(d, options)
    end unless first.wday == first_weekday

    first.upto(last) do |cur|
      cell_text, cell_attrs = yield cur
      cell_text  ||= cur.mday
      cell_attrs ||= {}
      cell_attrs[:headers] = th_id(cur, options[:table_id])
      cell_attrs[:class] ||= options[:day_class]
      cell_attrs[:class] += " weekend" if [0, 6].include?(cur.wday)
      today = (Time.respond_to?(:zone) && !(zone = Time.zone).nil? ? zone.now.to_date : Date.today)
      cell_attrs[:class] += " today" if (cur == today) and options[:show_today]

      cal << "<td class='weekNumber'>S#{cur.strftime("%W").to_s}</td>" if cur.wday == first_weekday

      cal << generate_cell(cell_text, cell_attrs)
      cal << "</tr><tr>" if cur.wday == last_weekday
    end

    # next month
    (last + 1).upto(beginning_of_week(last + 7, first_weekday) - 1)  do |d|
      cal << generate_other_month_cell(d, options)
    end unless last.wday == last_weekday

    cal << "</tr></tbody></table>"
    cal.respond_to?(:html_safe) ? cal.html_safe : cal
  end

  private

  def first_day_of_week(day)
    day
  end

  def last_day_of_week(day)
    if day > 0
      day - 1
    else
      6
    end
  end

  def days_between(first, second)
    if first > second
      second + (7 - first)
    else
      second - first
    end
  end

  def beginning_of_week(date, start = 1)
    days_to_beg = days_between(start, date.wday)
    date - days_to_beg
  end

  def generate_cell(cell_text, cell_attrs)
    cell_attrs = cell_attrs.map {|k, v| %(#{k}="#{v}") }.join(" ")
    "<td #{cell_attrs}>#{cell_text}</td>"
  end

  def generate_other_month_cell(date, options)
    cell_attrs = {}
    cell_attrs[:headers] = th_id(date, options[:table_id])
    cell_attrs[:class] = options[:other_month_class]
    cell_attrs[:class] += " weekend" if weekend?(date)
    cell_attrs[:title] ||= date.strftime("%W").to_i if options[:first_day_of_week] == 1

    cell_text = date.day
    if options[:accessible]
      cell_text += %(<span class="hidden"> #{month_names[date.month]}</span>)
    end

    generate_cell(date.day, cell_attrs)
  end

  # Calculates id for th element.
  #   derived from calendar_id and dow.
  #
  # Params:
  #   `day` can be either Date or DOW('Sunday', 'Monday')
  def th_id(day, calendar_id)
    return th_id(Date::DAYNAMES[day.wday], calendar_id) if day.is_a?(Date)
    "#{calendar_id}-#{day[0..2].downcase}"
  end

  def weekend?(date)
    [0, 6].include?(date.wday)
  end

  class Engine < Rails::Engine # :nodoc:
    ActiveSupport.on_load(:action_view) do
      include CalendarHelper
    end
  end if defined? Rails::Engine

end

app/views/time_tables/_filter.html.slim
= simple_form_for @search, url: request.path, method: "GET", html: { class: 'flex items-center tailwind-filters bg-grey relative pr-6' }, wrapper: :filters_form_tailwind  do |f|
  = f.simple_fields_for :order, @search.order, defaults: { wrapper: false } do |form_order|
    - form_order.object.attributes.keys.each do |attribute|
      = form_order.input attribute, as: :hidden

  .flex.flex-col.w-full
    .flex.items-center.border-r.border-white
      = f.input :comment, label: false, wrapper_html: {class: "w-2/5"}, placeholder: I18n.t('simple_form.placeholders.search.text')
    .flex.items-center.border-t.border-r.border-white
      = f.label Chouette::TimeTable.human_attribute_name(:bounding_dates), required: false, class: 'control-label pl-6'
      = f.input :start_date, as: :date_picker
      = f.input :end_date, as: :date_picker

  .flex.flex-col.justify-center.items-center.actions.ml-auto.py-3.w-80
    .flex.items-center.mb-3
      = render partial: 'shared/per_page', locals: {f:f}
    .flex.items-center
      = link_to t('actions.erase'), workbench_referential_time_tables_path(@workbench, @referential), class: 'btn btn-link'
      = f.submit t('actions.filter'), class: 'btn btn-default'

app/views/time_tables/_form.html.slim
= simple_form_for [@workbench, @referential, @time_table], html: {class: 'form-horizontal', id: 'timetable_form'}, wrapper: :horizontal_form do |form|

  .row
    .col-lg-12
      = form.input :comment, :input_html => { :title => t("formtastic.titles#{format_restriction_for_locales(@referential)}.time_table.comment")}

      - if @time_table.new_record? && !@time_table.created_from
        = form.input :calendar_id,
          as: :ajax_select,
          collection: [],
          input_html: { 'data-url': calendars_workbench_autocomplete_index_path(@referential.workbench) }

      - if @time_table.created_from
        = form.input :created_from, disabled: true, input_html: { value: @time_table.created_from.comment }
        .hidden = form.input :created_from_id, as: :hidden

  = cancel_button
  = form.button :submit, t('actions.submit'), class: 'btn btn-default formSubmitr', form: 'timetable_form'

app/views/time_tables/_show_time_table.html.slim
.row
  - (1..12).each_slice(4).each do |chunk|
    .row.flex.items-center.justify-between
      - chunk.each do |month|
          .col-lg-3.col-md-4.col-sm-4.col-xs-6
            = new_alt_calendar(year: @year, month: month, first_day_of_week: 1, calendar_title: "#{I18n.t("date.month_names")[month]}", show_today: false) do |d|
              - if time_table.include_day?(d)
                - [ link_to(d.mday, '#', {disabled: disabled}), {class: "day operating_day", title: 'Voir'} ]

app/views/time_tables/edit.html.slim
- breadcrumb :time_table, @workbench, @referential, @time_table
- page_header_content_for @time_table
- content_for :page_header_title, t('time_tables.show.title', name: @time_table.comment), flush: true

.page_content
  .container-fluid
    #periods

= javascript_tag do
  | window.actionType = "#{raw params[:action]}";
  // | window.I18n = #{(I18n.backend.send(:translations)[I18n.locale].to_json).html_safe};
  | window.timetablesUrl = "#{workbench_referential_time_table_path(@workbench, @referential, @time_table).html_safe}";
  | window.redirectUrl = window.timetablesUrl;
  | window.available_code_spaces = #{(@referential.workgroup&.code_spaces.to_json)&.html_safe};

app/views/time_tables/index.html.slim
- breadcrumb :time_tables, @workbench, @referential

.page_content
  .container-fluid
    .row
      .col-lg-12
        = render 'filter'

    - if @time_tables.any?
      .row
        .col-lg-12
          = table_builder_2 @time_tables,
            [ \
              TableBuilderHelper::Column.new( \
                name: 'ID', \
                attribute: Proc.new { |n| n.get_objectid.short_id}, \
                sortable: false \
              ), \
              TableBuilderHelper::Column.new( \
                key: :color, \
                attribute: Proc.new { |tt| tt.color ? content_tag(:span, '', class: 'fa fa-circle', style: "color:#{tt.color}") : '-' }, \
              ), \
              TableBuilderHelper::Column.new( \
                key: :comment, \
                attribute: 'comment', \
                link_to: lambda do |time_table| \
                  workbench_referential_time_table_path(@workbench, @referential, time_table) \
                end \
              ), \
              TableBuilderHelper::Column.new( \
                key: :bounding_dates, \
                attribute: Proc.new { |tt| tt.object.bounding_dates.empty? ? '-' : t('bounding_dates', debut: l(tt.object.bounding_dates.min), end: l(tt.object.bounding_dates.max)) }, \
                sortable: false \
              ), \
              TableBuilderHelper::Column.new( \
                key: :vehicle_journeys_count, \
                name: Chouette::TimeTable.tmf('associated_vehicle_journeys'), \
                attribute: Proc.new{ |tt| tt.vehicle_journeys.count }, \
                sortable: false, \
                link_to: lambda do |time_table| \
                  workbench_referential_vehicle_journeys_path(@workbench, @referential, :'search[time_table_id]' => time_table.id) \
                end \
              ), \
              TableBuilderHelper::Column.new( \
                name: Chouette::TimeTable.tmf('day_types'), \
                attribute: Proc.new { |tt| (%w(monday tuesday wednesday thursday friday saturday sunday).collect{|d| tt.send(d) ? t("calendars.days.#{d}") : '' }).reject{|a| a.empty?}.join(', ').html_safe }, \
                sortable: false \
              ), \
              TableBuilderHelper::Column.new( \
                key: :calendar, \
                attribute: Proc.new { |tt| tt.calendar ? tt.calendar.try(:name) : '-' } \
              ), \
              TableBuilderHelper::Column.new( \
                key: :updated_at, \
                attribute: Proc.new { |tt| l(tt.updated_at) } \
              ) \
            ],
            cls: 'table has-search'

          = new_pagination @time_tables, 'pull-right'

    - unless @time_tables.any?
      .row.mt-xs
        .col-lg-12
          = replacement_msg t('time_tables.search_no_results')

app/views/time_tables/new.html.slim
- breadcrumb :time_tables, @workbench, @referential
.page_content
  .container-fluid
    .row
      .col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1
        = render 'form'

app/views/time_tables/show.html.slim
- require 'calendar_helper'
- breadcrumb :time_table, @workbench, @referential, @time_table
- page_header_content_for @time_table

- content_for :page_header_title, t('time_tables.show.title', name: @time_table.comment), flush: true

.page_content
  .container-fluid
    .row
      .col-lg-6.col-md-6.col-sm-12.col-xs-12
        = simple_block_for @time_table, title: t("metadatas") do |d|
          = d.attribute :bounding_dates, value: (@time_table.bounding_dates.empty? ? '-' : t('bounding_dates', debut: l(@time_table.bounding_dates.min), end: l(@time_table.bounding_dates.max)))
          = d.attribute :color, as: :color
          = d.attribute :calendar, as: :association
          = d.attribute :day_types, value: %w(monday tuesday wednesday thursday friday saturday sunday).collect{ |d| content_tag(:span, t("calendars.days.#{d}"), class: "label label-default #{@time_table.send(d) ? '' : 'disabled'}") }.join.html_safe
          = d.attribute :checksum

        = render 'codes/block', model: @time_table

    .row
      .col-lg-12.mb-sm
        .pagination.pull-right
          = @year
          .page_links
            = link_to '', workbench_referential_time_table_path(@workbench, @referential, @time_table, year: (@year - 1)), class: 'previous_page'
            = link_to '', workbench_referential_time_table_path(@workbench, @referential, @time_table, year: (@year + 1)), class: 'next_page'

    = render 'show_time_table', time_table: @time_table, edit_url: [:edit, @referential, @time_table], disabled: !resource_policy.update?