config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :dashboard, only: :show
  resource :subscriptions, only: :create

  # Used to the redirect user to the current workbench
  # See CHOUETTE-797
  namespace :redirect do
    resources :lines, only: :show
    resources :companies, only: :show
    resources :stop_areas, only: :show
  end

  resources :workbenches, only: %i[show] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    resources :api_keys

    resources :autocomplete, only: [] do
      get :lines, on: :collection, defaults: { format: 'json' }
      get :companies, on: :collection, defaults: { format: 'json' }
      get :line_providers, on: :collection, defaults: { format: 'json' }
      get :line_notices, on: :collection, defaults: { format: 'json' }
      get :stop_areas, on: :collection, defaults: { format: 'json' }
      get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
      get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      get :users, on: :collection, defaults: { format: 'json' }
      get :macro_lists, on: :collection, defaults: { format: 'json' }
      get :control_lists, on: :collection, defaults: { format: 'json' }
      get :calendars, on: :collection, defaults: { format: 'json' }
    end

    resource :output, controller: :workbench_outputs
    resources :merges do
      member do
        put :rollback
      end
      collection do
        get :available_referentials
      end
    end

    delete :referentials, on: :member, action: :delete_referentials
    resources :referentials do # rubocop:disable Metrics/BlockLength
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :autocomplete, controller: 'referential_autocomplete', only: [] do
        defaults format: :json do
          collection do
            get :companies
            get :lines
            get :journey_patterns
            get :time_tables
            get :vehicle_journeys
          end
        end
      end

      member do
        put :archive
        put :unarchive
        get :journey_patterns
      end

      resources :autocomplete, only: [] do
        get :line_providers, on: :collection, defaults: { format: 'json' }
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end

      resources :lines, controller: 'referential_lines', only: %i[show] do # rubocop:disable Metrics/BlockLength
        resources :footnotes do
          collection do
            get 'edit_all'
            patch 'update_all'
          end
        end

        resources :routes do # rubocop:disable Metrics/BlockLength
          member do
            get 'edit_boarding_alighting'
            put 'save_boarding_alighting'
            post 'duplicate', to: 'routes#duplicate'
            get 'retrieve_nearby_stop_areas'
            get 'autocomplete_stop_areas'
          end
          collection do
            get 'fetch_opposite_routes'
            get 'fetch_user_permissions'
          end
          resource :journey_patterns, only: %i[show update], controller: :journey_patterns_collections
          resources :journey_patterns, only: [] do
            member do
              get 'available_specific_stop_places'
              put 'unassociate_shape'
              put 'duplicate'
            end

            resource :shapes, except: :index, module: 'journey_pattern' do
              collection do
                defaults format: :json do
                  get :get_user_permissions
                  put :update_line
                end
              end
            end
          end
        end
        resources :routing_constraint_zones
      end

      resources :routes, only: [] do
        resource :vehicle_journeys, only: %i[show update], controller: :route_vehicle_journeys
      end

      resources :vehicle_journeys, controller: 'referential_vehicle_journeys', only: [:index]

      resources :time_tables do
        member do
          post 'actualize'
          get 'duplicate'
          get 'month', defaults: { format: :json }
        end
      end
      resources :clean_ups

      scope module: 'redirect', only: :show do
        resources :routes
        resources :journey_patterns
        resources :vehicle_journeys
      end

      resources :service_counts, only: %i[index]
    end

    resources :notification_rules
    resources :macro_lists do
      resources :macro_list_runs, only: %w[new create]
    end

    resources :sources do
      post :retrieve, on: :member
    end

    concern :macro_runs do
      resources :macro_runs, only: [] do
        resources :macro_messages, only: :index
      end
    end

    resources :macro_list_runs, only: %w[new create show index], concerns: :macro_runs do
      resources :macro_context_runs, only: [], concerns: :macro_runs
    end

    resources :control_lists do
      resources :control_list_runs, only: %w[new create]
    end

    concern :control_runs do
      resources :control_runs, only: [] do
        resources :control_messages, only: :index
      end
    end

    resources :control_list_runs, only: %w[new create show index], concerns: :control_runs do
      resources :control_context_runs, only: [], concerns: :control_runs
    end

    resource :stop_area_referential, only: %i[show edit update] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :stop_area_routing_constraints
      resources :entrances
      resources :stop_area_groups

      resources :stop_area_providers

      resources :stop_areas do
        get :autocomplete, on: :collection
        get :fetch_connection_links, on: :member, defaults: { format: 'geojson' }

        resources :document_memberships, only: %i[index create destroy], controller: :stop_area_document_memberships
      end

      resources :autocomplete, only: [] do
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end
      resources :connection_links do
        get :get_connection_speeds, on: :collection, defaults: { format: 'json' }
      end
    end

    resource :line_referential, only: %i[show] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
      resources :line_routing_constraint_zones
      resources :line_groups

      resources :line_providers

      resources :lines do
        get :autocomplete, on: :collection

        resources :line_notice_memberships, only: %i[index new create destroy]
        get 'line_notice_memberships/edit', to: 'line_notice_memberships_collections#edit'
        patch 'line_notice_memberships', to: 'line_notice_memberships_collections#update'

        resources :document_memberships, only: %i[index create destroy], controller: :line_document_memberships
      end

      resources :companies do
        get :autocomplete, on: :collection

        resources :document_memberships, only: %i[index create destroy], controller: :company_document_memberships
      end

      resources :networks
      resources :line_notices
      resources :booking_arrangements
    end

    resource :shape_referential, only: [] do
      resources :shapes, except: [:create]
      resources :point_of_interests
      resources :point_of_interest_categories
      resources :service_facility_sets

      resources :accessibility_assessments do
        get :autocomplete, on: :collection
      end
    end

    resources :contracts

    resources :sequences

    resources :documents do
      get :download, on: :member
    end

    resources :document_providers

    resources :fare_zones
    resources :fare_providers

    resources :processing_rules, as: 'processing_rule_workbenches'

    resources :calendars do
      member do
        get 'month', defaults: { format: :json }
      end
    end

    resources :imports do
      get :download, on: :member
      get :internal_download, on: :member
    end

    get 'imports/:id/import_resources/:import_resource_id/messages',
        to: 'imports#messages',
        as: 'import_import_resource_import_messages'

    resources :exports do
      get :download, on: :member
    end
  end

  resource :workbench_confirmation, only: %i[new create]

  resources :workgroups, except: [:destroy] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    put :setup_deletion, on: :member
    put :remove_deletion, on: :member

    member do
      get :edit_aggregate
      get :edit_merge
    end

    resources :code_spaces, except: :destroy

    resources :document_types
    resources :processing_rules, as: 'processing_rule_workgroups', controller: 'workgroup_processing_rules'

    resources :workbenches, controller: :workgroup_workbenches, only: %i[new create show edit update] do
      resources :sharings, controller: 'workbench/sharings', only: %i[new create show destroy]
    end

    resource :output, controller: :workgroup_outputs
    resources :aggregates do
      member do
        put :rollback
      end
    end

    resources :publication_setups do
      resources :publications, only: [:create, :show]
    end

    resources :publication_apis do
      resources :publication_api_keys
    end

    resources :control_list_runs, controller: :workgroup_control_list_runs, only: %w[show index] do
      resources :control_runs, only: [] do

app/controllers/referential_vehicle_journeys_controller.rb
# frozen_string_literal: true

# Browse all VehicleJourneys of the Referential
class ReferentialVehicleJourneysController < Chouette::ReferentialController
  defaults resource_class: Chouette::VehicleJourney, collection_name: :vehicle_journeys

  respond_to :html, only: :index

  def index
    index! do
      @vehicle_journeys_for_paginate = search.dup.without_order.search(scope)
      @enable_complex_sort = @vehicle_journeys_for_paginate.count < 50_000

      search_scope = scope
      search_scope = scope.with_departure_arrival_second_offsets if @enable_complex_sort

      @vehicle_journeys = decorate_collection(search.search(search_scope))
    end
  end

  protected

  def scope
    parent.vehicle_journeys
  end

  def search
    @search ||= Search::VehicleJourney.from_params(params, referential: referential)
  end

  def decorate_collection(vehicle_journeys)
    VehicleJourneyDecorator.decorate(
      vehicle_journeys,
      context: {
        referential: referential,
        workbench: current_workbench
      }
    )
  end
end

app/views/referential_vehicle_journeys/_filters.html.slim
= simple_form_for @search, url: request.path, method: "GET", html: { class: 'flex items-center tailwind-filters bg-grey relative pr-6' }, wrapper: :filters_form_tailwind  do |f|
  = f.simple_fields_for :order, @search.order, defaults: { wrapper: false } do |form_order|
    - form_order.object.attributes.keys.each do |attribute|
      = form_order.input attribute, as: :hidden

  .flex.flex-col.w-full
    .flex.items-center.border-r.border-white
      = f.input :text, label: false, wrapper_html: {class: "w-2/5"}
    .flex.items-center.border-t.border-r.border-white
      = f.input :company_id, placeholder: I18n.t('simple_form.placeholders.search.company_id'), as: :tom_select, collection: @search.candidate_companies.map { |l| {id: l.id, text: l.display_name } }, wrapper_html: {class: "w-2/6"}
      = f.input :line_id, placeholder: I18n.t('simple_form.placeholders.search.line_id'), as: :tom_select, collection: @search.candidate_lines.map { |l| {id: l.id, text: l.display_name } }, wrapper_html: {class: "w-2/6"}
      = f.label :stop_area, class: 'pl-6 whitespace-nowrap'
      = f.input :from_stop_area_id, placeholder: I18n.t('simple_form.placeholders.search.stop_area_id'),
        as: :ajax_select,
        collection: @search.selected_from_stop_area_collection,
        label_method: :display_name,
        input_html: { 'data-url': stop_areas_workbench_referential_autocomplete_index_url(@workbench, current_referential) },
        wrapper_html: {class: "w-1/3"}
      = f.input :to_stop_area_id, placeholder: I18n.t('simple_form.placeholders.search.stop_area_id'),
        as: :ajax_select,
        collection: @search.selected_to_stop_area_collection,
        label_method: :display_name,
        input_html: { 'data-url': stop_areas_workbench_referential_autocomplete_index_url(@workbench, current_referential) },
        wrapper_html: {class: "w-1/3"}
    .flex.items-center.border-t.border-white
      = f.input :time_table_id, placeholder: I18n.t('simple_form.placeholders.search.time_table_id'),
        as: :ajax_select,
        collection: @search.candidate_time_tables,
        label_method: :display_name,
        input_html: { 'data-url': time_tables_workbench_referential_autocomplete_index_url(@workbench, current_referential) },
        wrapper_html: {class: "w-2/6"}
      = f.input :start_date, as: :date_picker
      = f.input :end_date, as: :date_picker

  .flex.flex-col.justify-center.items-center.actions.ml-auto.py-3.w-80
    .flex.items-center.mb-3
      = render partial: 'shared/per_page', locals: {f:f}
    .flex.items-center
      = link_to t('actions.erase'), [@workbench, @parent, :vehicle_journeys], class: 'btn btn-link'
      = f.submit t('actions.filter'), class: 'btn btn-default'

app/views/referential_vehicle_journeys/index.html.slim
- breadcrumb :referential_vehicle_journeys, @workbench, @referential
- content_for :page_header_title, t('.title')

.page_content
  .container-fluid
    .form-group
      .row
        .col-lg-12
          = render 'filters'
    - if @vehicle_journeys&.any?
      .row
        .col-lg-12
          .select_table
            = table_builder_2 @vehicle_journeys,
              [ \
                TableBuilderHelper::Column.new( \
                  name: t('objectid'), \
                  attribute: Proc.new { |n| n.get_objectid.short_id }, \
                  sortable: false \
                ), \
                TableBuilderHelper::Column.new( \
                  key: :published_journey_name,
                  attribute: Proc.new {|v| v.published_journey_name.presence||I18n.t('none')},
                  link_to: lambda { |vehicle_journey| workbench_referential_route_vehicle_journeys_path(@workbench, @referential, vehicle_journey.route) } \
                ),
                TableBuilderHelper::Column.new( \
                  key: :line, \
                  attribute: Proc.new {|v| v.route.line.name}, \
                  sortable: false,
                  link_to: lambda { |vehicle_journey| workbench_referential_line_path(@workbench, @referential, vehicle_journey.route.line) } \
                ), \
                TableBuilderHelper::Column.new( \
                  key: :company, \
                  attribute: Proc.new {|v| v.route.line.company&.name}, \
                  sortable: false \
                ), \
                TableBuilderHelper::Column.new( \
                  key: :route,
                  attribute: Proc.new {|v| v.route.name},
                  sortable: false,
                  link_to: lambda { |vehicle_journey| workbench_referential_line_route_path(@workbench, @referential, vehicle_journey.route.line, vehicle_journey.route) } \
                ),
                TableBuilderHelper::Column.new( \
                  key: :departure_time, \
                  attribute: Proc.new {|v| display_time_of_day(v.vehicle_journey_at_stops.first&.departure_local_time_of_day) }, \
                  sortable: @enable_complex_sort \
                ), \
                [@search.from_stop_area, @search.to_stop_area].compact.map{|stop| \
                  TableBuilderHelper::Column.new( \
                    attribute: Proc.new {|v| vjas = v.vehicle_journey_at_stops.where("stop_points.stop_area_id" => stop.id).last; vjas && display_time_of_day(vjas.arrival_local_time_of_day) }, \
                    sortable: false, \
                    name: stop.name \
                  )\
                }, \
                TableBuilderHelper::Column.new( \
                  key: :arrival_time, \
                  attribute: Proc.new {|v| display_time_of_day(v.vehicle_journey_at_stops.last&.arrival_local_time_of_day) }, \
                  sortable: @enable_complex_sort \
                ), \
              ].flatten.compact,
              cls: 'table has-filter has-search'

          = new_pagination @vehicle_journeys_for_paginate, 'pull-right'
    - else
      .row.mt-xs
        .col-lg-12
          = replacement_msg t('.search_no_results')