config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :dashboard, only: :show
  resource :subscriptions, only: :create

  # Used to the redirect user to the current workbench
  # See CHOUETTE-797
  namespace :redirect do
    resources :lines, only: :show
    resources :companies, only: :show
    resources :stop_areas, only: :show
  end

  resources :workbenches, only: %i[show] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    resources :api_keys

    resources :autocomplete, only: [] do
      get :lines, on: :collection, defaults: { format: 'json' }
      get :companies, on: :collection, defaults: { format: 'json' }
      get :line_providers, on: :collection, defaults: { format: 'json' }
      get :line_notices, on: :collection, defaults: { format: 'json' }
      get :stop_areas, on: :collection, defaults: { format: 'json' }
      get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
      get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      get :users, on: :collection, defaults: { format: 'json' }
      get :macro_lists, on: :collection, defaults: { format: 'json' }
      get :control_lists, on: :collection, defaults: { format: 'json' }
      get :calendars, on: :collection, defaults: { format: 'json' }
    end

    resource :output, controller: :workbench_outputs
    resources :merges do
      member do
        put :rollback
      end
      collection do
        get :available_referentials
      end
    end

    delete :referentials, on: :member, action: :delete_referentials
    resources :referentials do # rubocop:disable Metrics/BlockLength
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :autocomplete, controller: 'referential_autocomplete', only: [] do
        defaults format: :json do
          collection do
            get :companies
            get :lines
            get :journey_patterns
            get :time_tables
            get :vehicle_journeys
          end
        end
      end

      member do
        put :archive
        put :unarchive
        get :journey_patterns
      end

      resources :autocomplete, only: [] do
        get :line_providers, on: :collection, defaults: { format: 'json' }
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end

      resources :lines, controller: 'referential_lines', only: %i[show] do # rubocop:disable Metrics/BlockLength
        resources :footnotes do
          collection do
            get 'edit_all'
            patch 'update_all'
          end
        end

        resources :routes do # rubocop:disable Metrics/BlockLength
          member do
            get 'edit_boarding_alighting'
            put 'save_boarding_alighting'
            post 'duplicate', to: 'routes#duplicate'
            get 'retrieve_nearby_stop_areas'
            get 'autocomplete_stop_areas'
          end
          collection do
            get 'fetch_opposite_routes'
            get 'fetch_user_permissions'
          end
          resource :journey_patterns, only: %i[show update], controller: :journey_patterns_collections
          resources :journey_patterns, only: [] do
            member do
              get 'available_specific_stop_places'
              put 'unassociate_shape'
              put 'duplicate'
            end

            resource :shapes, except: :index, module: 'journey_pattern' do
              collection do
                defaults format: :json do
                  get :get_user_permissions
                  put :update_line
                end
              end
            end
          end
        end
        resources :routing_constraint_zones
      end

      resources :routes, only: [] do
        resource :vehicle_journeys, only: %i[show update], controller: :route_vehicle_journeys
      end

      resources :vehicle_journeys, controller: 'referential_vehicle_journeys', only: [:index]

      resources :time_tables do
        member do
          post 'actualize'
          get 'duplicate'
          get 'month', defaults: { format: :json }
        end
      end
      resources :clean_ups

      scope module: 'redirect', only: :show do
        resources :routes
        resources :journey_patterns
        resources :vehicle_journeys
      end

      resources :service_counts, only: %i[index]
    end

    resources :notification_rules
    resources :macro_lists do
      resources :macro_list_runs, only: %w[new create]
    end

    resources :sources do
      post :retrieve, on: :member
    end

    concern :macro_runs do
      resources :macro_runs, only: [] do
        resources :macro_messages, only: :index
      end
    end

    resources :macro_list_runs, only: %w[new create show index], concerns: :macro_runs do
      resources :macro_context_runs, only: [], concerns: :macro_runs
    end

    resources :control_lists do
      resources :control_list_runs, only: %w[new create]
    end

    concern :control_runs do
      resources :control_runs, only: [] do
        resources :control_messages, only: :index
      end
    end

    resources :control_list_runs, only: %w[new create show index], concerns: :control_runs do
      resources :control_context_runs, only: [], concerns: :control_runs
    end

    resource :stop_area_referential, only: %i[show edit update] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :stop_area_routing_constraints
      resources :entrances
      resources :stop_area_groups

      resources :stop_area_providers

      resources :stop_areas do
        get :autocomplete, on: :collection
        get :fetch_connection_links, on: :member, defaults: { format: 'geojson' }

        resources :document_memberships, only: %i[index create destroy], controller: :stop_area_document_memberships
      end

      resources :autocomplete, only: [] do
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end
      resources :connection_links do
        get :get_connection_speeds, on: :collection, defaults: { format: 'json' }
      end
    end

    resource :line_referential, only: %i[show] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
      resources :line_routing_constraint_zones
      resources :line_groups

      resources :line_providers

      resources :lines do
        get :autocomplete, on: :collection

        resources :line_notice_memberships, only: %i[index new create destroy]
        get 'line_notice_memberships/edit', to: 'line_notice_memberships_collections#edit'
        patch 'line_notice_memberships', to: 'line_notice_memberships_collections#update'

        resources :document_memberships, only: %i[index create destroy], controller: :line_document_memberships
      end

      resources :companies do
        get :autocomplete, on: :collection

        resources :document_memberships, only: %i[index create destroy], controller: :company_document_memberships
      end

      resources :networks
      resources :line_notices
      resources :booking_arrangements
    end

    resource :shape_referential, only: [] do
      resources :shapes, except: [:create]
      resources :point_of_interests
      resources :point_of_interest_categories
      resources :service_facility_sets

      resources :accessibility_assessments do
        get :autocomplete, on: :collection
      end
    end

    resources :contracts

    resources :sequences

    resources :documents do
      get :download, on: :member
    end

    resources :document_providers

    resources :fare_zones
    resources :fare_providers

    resources :processing_rules, as: 'processing_rule_workbenches'

    resources :calendars do
      member do
        get 'month', defaults: { format: :json }
      end
    end

    resources :imports do
      get :download, on: :member
      get :internal_download, on: :member
    end

    get 'imports/:id/import_resources/:import_resource_id/messages',
        to: 'imports#messages',
        as: 'import_import_resource_import_messages'

    resources :exports do
      get :download, on: :member
    end
  end

  resource :workbench_confirmation, only: %i[new create]

  resources :workgroups, except: [:destroy] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    put :setup_deletion, on: :member
    put :remove_deletion, on: :member

    member do
      get :edit_aggregate
      get :edit_merge
    end

    resources :code_spaces, except: :destroy

    resources :document_types
    resources :processing_rules, as: 'processing_rule_workgroups', controller: 'workgroup_processing_rules'

    resources :workbenches, controller: :workgroup_workbenches, only: %i[new create show edit update] do
      resources :sharings, controller: 'workbench/sharings', only: %i[new create show destroy]
    end

    resource :output, controller: :workgroup_outputs
    resources :aggregates do
      member do
        put :rollback
      end
    end

    resources :publication_setups do
      resources :publications, only: [:create, :show]
    end

    resources :publication_apis do
      resources :publication_api_keys
    end

    resources :control_list_runs, controller: :workgroup_control_list_runs, only: %w[show index] do
      resources :control_runs, only: [] do

app/controllers/api/v1/stop_area_referentials_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class StopAreaReferentialsController < WorkbenchController
      respond_to :json, :xml
      wrap_parameters :stop_area_referential, include: [:type, *WebhookEvent::StopAreaReferential.resource_names]

      before_action :authenticate

      def webhook
        if event.valid?
          if event.update_or_create?
            synchronization.source = event.netex_source
            synchronization.update_or_create
          end

          if event.destroyed?
            deleted_ids = event.stop_place_ids + event.quay_ids
            synchronization.delete deleted_ids
          end

          logger.info "Synchronization done: #{counters}"
          render json: counters.to_hash, status: :ok
        else
          render json: { message: event.errors.full_messages }, status: :unprocessable_entity
        end
      end

      protected

      def event
        @event ||= WebhookEvent::StopAreaReferential.new event_params
      end

      def counters
        @counters ||= Chouette::Sync::Counters.new
      end

      def synchronization
        @synchronization ||=
          Chouette::Sync::StopArea::Netex.new target: stop_area_provider, event_handler: counters.event_handler
      end

      def stop_area_provider
        @stop_area_provider ||= workbench.default_stop_area_provider
      end

      def workbench
        @workbench = current_workgroup.workbenches.find(params[:id])
      end

      attr_reader :current_workgroup

      private

      def event_params
        params.require(:stop_area_referential).permit(*permitted_attributes)
      end

      # Accepts
      # * normal attributes
      # * hash attributes for single resources
      # * array of hash with id parameter for several resources
      #
      # [ "type", "stop_place", "stop_places", "quay", "quays",
      #   {"stop_place"=>{}, "stop_places"=>[:id], "quay"=>{}, "quays"=>[:id]}]
      def permitted_attributes
        @permitted_attributes ||= [
          'type',
          *WebhookEvent::StopAreaReferential.resource_names,
          Hash[WebhookEvent::StopAreaReferential.resource_names.map { |name| [name, name.end_with?('s') ? [:id] : {}] }]
        ]
      end

      def authenticate
        authenticate_or_request_with_http_token do |token|
          api_key = ApiKey.find_by token: token
          @current_workgroup = api_key&.workgroup

          @current_workgroup.present?
        end
      end
    end
  end
end

app/controllers/chouette/stop_area_referential_controller.rb
# frozen_string_literal: true

module Chouette
  class StopAreaReferentialController < WorkbenchController
    # To prevent a "chouette_" to be added to all its chidren
    resources_configuration[:self].delete(:route_prefix)

    include ControllerResourceValidations

    belongs_to :stop_area_referential, singleton: true

    def stop_area_referential
      association_chain
      get_parent_ivar(:stop_area_referential)
    end

    def current_referential
      stop_area_referential
    rescue ::ActiveRecord::RecordNotFound
      nil
    end
    helper_method :current_referential

    protected

    def build_resource
      get_resource_ivar || set_resource_ivar(
        apply_scopes_if_available(
          stop_area_provider_for_build.send(method_for_association_chain)
        ).send(method_for_build, resource_params[0].merge(stop_area_referential: stop_area_referential))
      )
    end

    def controller_resource_validations(object)
      errors = super
      unless object.new_record? || candidate_stop_area_providers.include?(object.stop_area_provider)
        errors << %i[stop_area_provider_id invalid]
      end
      errors
    end

    def parent_for_parent_policy
      if params[:id]
        resource.stop_area_provider
      else
        stop_area_provider_for_build
      end
    end

    private

    def stop_area_provider_from_params
      return nil unless params[resource_instance_name] \
                     && params[resource_instance_name][:stop_area_provider_id].present?

      candidate_stop_area_providers.find(params[resource_instance_name][:stop_area_provider_id])
    end

    def stop_area_provider_for_build
      @stop_area_provider_for_build ||= stop_area_provider_from_params || current_workbench.default_stop_area_provider
    end

    def candidate_stop_area_providers
      @candidate_stop_area_providers ||= current_workbench.stop_area_providers.order(:name)
    end
    helper_method :candidate_stop_area_providers
  end
end

app/controllers/stop_area_referentials_controller.rb
# frozen_string_literal: true

class StopAreaReferentialsController < Chouette::WorkbenchController
  defaults resource_class: StopAreaReferential, singleton: true

  def show # rubocop:disable Metrics/MethodLength
    show! do
      @stop_area_referential = StopAreaReferentialDecorator.decorate(
        @stop_area_referential,
        context: {
          workbench: workbench
        }
      )
      @connection_links = ConnectionLinkDecorator.decorate(
        @stop_area_referential.connection_links.order('updated_at desc').limit(5)
      )
      @entrances = EntranceDecorator.decorate(@entrances)
    end
  end

  protected

  def stop_area_referential_params
    locales = []
    params[:locales].each do |_, locale|
      next if locale[:delete] == '1'

      locales << {
        code: StopAreaReferential.translate_code_to_internal(locale[:code]),
        default: locale[:default] == '1'
      }
    end if params[:locales]

    stops_selection_displayed_fields = {}
    params[:stops_selection_displayed_fields].each do |k, v|
      stops_selection_displayed_fields[k] = v == '1'
    end if params[:stops_selection_displayed_fields]

    route_edition_available_stops = {}
    params[:route_edition_available_stops].each do |k, v|
      route_edition_available_stops[k] = v == '1'
    end if params[:route_edition_available_stops]

    { locales: locales, stops_selection_displayed_fields: stops_selection_displayed_fields, route_edition_available_stops: route_edition_available_stops }
  end
end

app/views/stop_area_referentials/_form.html.slim
= simple_form_for @stop_area_referential, url: workbench_stop_area_referential_path(@workbench), html: {class: 'form-horizontal', id: 'stop_area_referential_form'}, wrapper: :horizontal_form do |f|
  legend= StopAreaReferential.tmf(:stops_selection_displayed_fields)
  .row.locales
    .col-lg-12
      .row
        .col-md-4
          label{for="stops_selection_displayed_fields_name"}= Chouette::StopArea.tmf(:name)
        .col-md-8
          = check_box "stops_selection_displayed_fields", :name, checked: true, disabled: true

      - StopAreaReferential::STOPS_SELECTION_DISPLAYABLE_FIELDS.each do |f|
        .row
          .col-md-4
            label{for="stops_selection_displayed_fields_#{f}"}= StopAreaReferential.tmf(f)
          .col-md-8
            = check_box "stops_selection_displayed_fields", f, checked: @stop_area_referential.stops_selection_displayed_fields[f.to_s]


  - if has_feature?(:stop_area_localized_names)
    br
    legend= StopAreaReferential.tmf(:locales)
    .row.header
      .col-md-1
      .col-md-3= StopAreaReferential.tmf(:locale_name)
      .col-md-3= StopAreaReferential.tmf(:locale_code)
      .col-md-2= StopAreaReferential.tmf(:locale_default)
      .col-md-3= 'actions.delete'.t
    .locales
      - f.object.sorted_locales.each_with_index do |locale, i|
        .row
          .col-md-1= label_for_country @stop_area_referential.translate_code_to_official(locale['code'])
          .col-md-3= @stop_area_referential.locale_name(locale)
          .col-md-3
            = locale['code']
            = hidden_field "locales[#{i}]", :code, value: locale['code']
          .col-md-2= check_box "locales[#{i}]", :default, checked: locale['default']
          .col-md-3
            = hidden_field "locales[#{i}]", :delete, value: 0
            = link_to '#', class: 'delete-locale', title: 'actions.delete'.t do
              = fa_icon :trash

    .row.add-locales
      - used_countries = @stop_area_referential.locales.map { |l| StopAreaReferential.translate_code_to_official(l['code']).split('_').last }
      - countries = ISO3166::Country.all.select { |c| ! used_countries.include?(c.alpha2) }
      - countries = countries.sort_by { |c| c.translation(I18n.locale)}
      - options = countries.map { |c| "<option id='#{c.alpha2}' code='#{StopAreaReferential.translate_code_to_internal("#{c.languages.first}_#{c.alpha2}")}'>#{c.translation(I18n.locale)}</option>" }.join('')
      .col-md-12
        = select_tag :add_locale, raw(options.html_safe), 'data-select2ed': 'true', class: 'country-select select2-resize'
        = link_to '#', class: 'btn btn-primary add-locale' do
          = fa_icon :plus, {text: 'actions.add'.t}

  - unless has_feature?("route_stop_areas_all_types")
    br
    legend= StopAreaReferential.tmf(:route_edition_available_stops)
    .row.locales
      - Chouette::AreaType::COMMERCIAL.each do |f|
          .row
            .col-md-4
              label{for="route_edition_available_stops_#{f}"}= t("area_types.label.#{f}")
            .col-md-8
              = check_box "route_edition_available_stops", f, checked: @stop_area_referential.route_edition_available_stops[f.to_s]

  = cancel_button
  = f.button :submit, t('actions.submit'), class: 'btn btn-default formSubmitr', form: 'stop_area_referential_form'

coffee:
  $('.add-locale').click (e)->
    option = $('#add_locale').find('option:selected')
    return unless option.length > 0

    i = $('.locales > .row').length
    row  = $("<div class='row'></div>")
    flag = $("<div class='col-md-1'><span title='#{option.html()}' class='flag-icon flag-icon-#{option.attr('id').toLowerCase()}'></span></div>")
    flag.appendTo row
    name = $("<div class='col-md-3'>#{option.html()}</div>")
    name.appendTo row
    code = $("<div class='col-md-3'><input name='locales[#{i}][code]' type='hidden' value='#{option.attr('code')}'>#{option.attr('code')}</div>")
    code.appendTo row
    default_locale = $("<div class='col-md-2'><input name='locales[#{i}][default]' type='hidden' value='0'><input type='checkbox' value='1' name='locales[#{i}][default]' id='locales_#{i}_default'></div>")
    default_locale.appendTo row
    delete_locale = $("<div class='col-md-3'><input name='locales[#{i}][delete]' type='hidden' value='0'><a class='delete-locale' title='Supprimer' href='#'><i class='fa fa-trash'></i></a></div>")
    delete_locale.appendTo row
    row.appendTo $('.locales')
    option.remove()
    initDeleteButtons()
    e.preventDefault()
    false

  initDeleteButtons = ->
    $('a.delete-locale').click (e) ->
      hidden = $(e.currentTarget).parent().find('input[type=hidden]')
      hidden.val 1
      $(e.currentTarget).parents('.row').addClass('deleted')
      e.preventDefault()
      false

  initDeleteButtons()

app/views/stop_area_referentials/edit.html.slim
- breadcrumb :stop_area_referential, @workbench
- content_for :page_header_title, StopAreaReferential.ts.capitalize

.page_content
  .container-fluid
    .row
      .col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1
        = render 'form'

app/views/stop_area_referentials/show.html.slim
- breadcrumb :stop_area_referential, @workbench
- content_for :page_header_title, StopAreaReferential.ts.capitalize

.page_content.stop_area_referential_show
  .container-fluid
    .row
      .col-sm-4.col-xs-12
        .panel.panel-default
          .panel-heading
            h3.panel-title.with_actions
              div
                = link_to Chouette::StopArea.t, workbench_stop_area_referential_stop_areas_path(@workbench)
                span.badge.ml-xs =  @stop_area_referential.stop_areas.count
              div
                = link_to '', workbench_stop_area_referential_stop_areas_path(@workbench), class: ' fa fa-chevron-right pull-right', title: t('workbenches.index.offers.see')
          .list-group
            - @stop_area_referential.stop_areas.order("updated_at desc").limit(5).each do |stop_area|
              .list-group-item
                = link_to stop_area.name, workbench_stop_area_referential_stop_area_path(@workbench, stop_area)
                =< t('date.updated', distance_in_time: time_ago_in_words(stop_area.updated_at))
            - unless @stop_area_referential.stop_areas.any?
              = replacement_msg t('no_result_text')

      .col-sm-offset-1.col-sm-4.col-xs-12
        .panel.panel-default
          .panel-heading
            h3.panel-title.with_actions
              div
                = link_to StopAreaProvider.t, workbench_stop_area_referential_stop_area_providers_path(@workbench)
                span.badge.ml-xs =  @stop_area_referential.stop_area_providers.count
              div
                = link_to '', workbench_stop_area_referential_stop_area_providers_path(@workbench), class: ' fa fa-chevron-right pull-right', title: t('workbenches.index.offers.see')
          .list-group
            - @stop_area_referential.stop_area_providers.order("updated_at desc").limit(5).each do |stop_area_provider|
              .list-group-item
                = link_to stop_area_provider.name, workbench_stop_area_referential_stop_area_provider_path(@workbench, stop_area_provider)
                =< t('date.updated', distance_in_time: time_ago_in_words(stop_area_provider.updated_at))
            - unless @stop_area_referential.stop_area_providers.any?
              = replacement_msg t('no_result_text')

    .row
      .col-sm-4.col-xs-12
        .panel.panel-default
          .panel-heading
            h3.panel-title.with_actions
              div
                = link_to Chouette::ConnectionLink.t, workbench_stop_area_referential_connection_links_path(@workbench)
                span.badge.ml-xs =  @stop_area_referential.connection_links.count
              div
                = link_to '', workbench_stop_area_referential_connection_links_path(@workbench), class: ' fa fa-chevron-right pull-right', title: t('workbenches.index.offers.see')
          .list-group
            - @connection_links.each do |connection_link|
              .list-group-item
                = link_to connection_link.name, workbench_stop_area_referential_connection_link_path(@workbench, connection_link)
                =< t('date.updated', distance_in_time: time_ago_in_words(connection_link.updated_at))
            - unless @stop_area_referential.connection_links.any?
              = replacement_msg t('no_result_text')

      .col-sm-offset-1.col-sm-4.col-xs-12
        .panel.panel-default
          .panel-heading
            h3.panel-title.with_actions
              div
                = link_to StopAreaRoutingConstraint.t, workbench_stop_area_referential_stop_area_routing_constraints_path(@workbench)
                span.badge.ml-xs =  @stop_area_referential.stop_area_routing_constraints.count
              div
                = link_to '', workbench_stop_area_referential_stop_area_routing_constraints_path(@workbench), class: ' fa fa-chevron-right pull-right', title: t('workbenches.index.offers.see')
          .list-group
            - @stop_area_referential.stop_area_routing_constraints.order("updated_at desc").limit(5).each do |constraint|
              .list-group-item
                = link_to constraint.name, workbench_stop_area_referential_stop_area_routing_constraint_path(@workbench, constraint)
                =< t('date.updated', distance_in_time: time_ago_in_words(constraint.updated_at))
            - unless @stop_area_referential.stop_area_routing_constraints.any?
              = replacement_msg t('no_result_text')
    .row
      .col-sm-4.col-xs-12
        .panel.panel-default
          .panel-heading
            h3.panel-title.with_actions
              div
                = link_to Entrance.t, workbench_stop_area_referential_entrances_path(@workbench)
                span.badge.ml-xs =  @stop_area_referential.entrances.count
              div
                = link_to '', workbench_stop_area_referential_entrances_path(@workbench), class: ' fa fa-chevron-right pull-right', title: t('workbenches.index.offers.see')
          .list-group
            - @stop_area_referential.entrances.order("updated_at desc").limit(5).each do |entrance|
              .list-group-item
                = link_to entrance.name, workbench_stop_area_referential_entrance_path(@workbench, entrance)
                =< t('date.updated', distance_in_time: time_ago_in_words(entrance.updated_at))
            - unless @stop_area_referential.entrances.any?
              = replacement_msg t('no_result_text')