config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  resource :dashboard, only: :show
  resource :subscriptions, only: :create

  # Used to the redirect user to the current workbench
  # See CHOUETTE-797
  namespace :redirect do
    resources :lines, only: :show
    resources :companies, only: :show
    resources :stop_areas, only: :show
  end

  resources :workbenches, only: %i[show] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    resources :api_keys

    resources :autocomplete, only: [] do
      get :lines, on: :collection, defaults: { format: 'json' }
      get :companies, on: :collection, defaults: { format: 'json' }
      get :line_providers, on: :collection, defaults: { format: 'json' }
      get :line_notices, on: :collection, defaults: { format: 'json' }
      get :stop_areas, on: :collection, defaults: { format: 'json' }
      get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
      get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      get :users, on: :collection, defaults: { format: 'json' }
      get :macro_lists, on: :collection, defaults: { format: 'json' }
      get :control_lists, on: :collection, defaults: { format: 'json' }
      get :calendars, on: :collection, defaults: { format: 'json' }
    end

    resource :output, controller: :workbench_outputs
    resources :merges do
      member do
        put :rollback
      end
      collection do
        get :available_referentials
      end
    end

    delete :referentials, on: :member, action: :delete_referentials
    resources :referentials do # rubocop:disable Metrics/BlockLength
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :autocomplete, controller: 'referential_autocomplete', only: [] do
        defaults format: :json do
          collection do
            get :companies
            get :lines
            get :journey_patterns
            get :time_tables
            get :vehicle_journeys
          end
        end
      end

      member do
        put :archive
        put :unarchive
        get :journey_patterns
      end

      resources :autocomplete, only: [] do
        get :line_providers, on: :collection, defaults: { format: 'json' }
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end

      resources :lines, controller: 'referential_lines', only: %i[show] do # rubocop:disable Metrics/BlockLength
        resources :footnotes do
          collection do
            get 'edit_all'
            patch 'update_all'
          end
        end

        resources :routes do # rubocop:disable Metrics/BlockLength
          member do
            get 'edit_boarding_alighting'
            put 'save_boarding_alighting'
            post 'duplicate', to: 'routes#duplicate'
            get 'retrieve_nearby_stop_areas'
            get 'autocomplete_stop_areas'
          end
          collection do
            get 'fetch_opposite_routes'
            get 'fetch_user_permissions'
          end
          resource :journey_patterns, only: %i[show update], controller: :journey_patterns_collections
          resources :journey_patterns, only: [] do
            member do
              get 'available_specific_stop_places'
              put 'unassociate_shape'
              put 'duplicate'
            end

            resource :shapes, except: :index, module: 'journey_pattern' do
              collection do
                defaults format: :json do
                  get :get_user_permissions
                  put :update_line
                end
              end
            end
          end
        end
        resources :routing_constraint_zones
      end

      resources :routes, only: [] do
        resource :vehicle_journeys, only: %i[show update], controller: :route_vehicle_journeys
      end

      resources :vehicle_journeys, controller: 'referential_vehicle_journeys', only: [:index]

      resources :time_tables do
        member do
          post 'actualize'
          get 'duplicate'
          get 'month', defaults: { format: :json }
        end
      end
      resources :clean_ups

      scope module: 'redirect', only: :show do
        resources :routes
        resources :journey_patterns
        resources :vehicle_journeys
      end

      resources :service_counts, only: %i[index]
    end

    resources :notification_rules
    resources :macro_lists do
      resources :macro_list_runs, only: %w[new create]
    end

    resources :sources do
      post :retrieve, on: :member
    end

    concern :macro_runs do
      resources :macro_runs, only: [] do
        resources :macro_messages, only: :index
      end
    end

    resources :macro_list_runs, only: %w[new create show index], concerns: :macro_runs do
      resources :macro_context_runs, only: [], concerns: :macro_runs
    end

    resources :control_lists do
      resources :control_list_runs, only: %w[new create]
    end

    concern :control_runs do
      resources :control_runs, only: [] do
        resources :control_messages, only: :index
      end
    end

    resources :control_list_runs, only: %w[new create show index], concerns: :control_runs do
      resources :control_context_runs, only: [], concerns: :control_runs
    end

    resource :stop_area_referential, only: %i[show edit update] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'

      resources :stop_area_routing_constraints
      resources :entrances
      resources :stop_area_groups

      resources :stop_area_providers

      resources :stop_areas do
        get :autocomplete, on: :collection
        get :fetch_connection_links, on: :member, defaults: { format: 'geojson' }

        resources :document_memberships, only: %i[index create destroy], controller: :stop_area_document_memberships
      end

      resources :autocomplete, only: [] do
        get :stop_areas, on: :collection, defaults: { format: 'json' }
        get :parent_stop_areas, on: :collection, defaults: { format: 'json' }
        get :stop_area_providers, on: :collection, defaults: { format: 'json' }
      end
      resources :connection_links do
        get :get_connection_speeds, on: :collection, defaults: { format: 'json' }
      end
    end

    resource :line_referential, only: %i[show] do
      resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
      resources :line_routing_constraint_zones
      resources :line_groups

      resources :line_providers

      resources :lines do
        get :autocomplete, on: :collection

        resources :line_notice_memberships, only: %i[index new create destroy]
        get 'line_notice_memberships/edit', to: 'line_notice_memberships_collections#edit'
        patch 'line_notice_memberships', to: 'line_notice_memberships_collections#update'

        resources :document_memberships, only: %i[index create destroy], controller: :line_document_memberships
      end

      resources :companies do
        get :autocomplete, on: :collection

        resources :document_memberships, only: %i[index create destroy], controller: :company_document_memberships
      end

      resources :networks
      resources :line_notices
      resources :booking_arrangements
    end

    resource :shape_referential, only: [] do
      resources :shapes, except: [:create]
      resources :point_of_interests
      resources :point_of_interest_categories
      resources :service_facility_sets

      resources :accessibility_assessments do
        get :autocomplete, on: :collection
      end
    end

    resources :contracts

    resources :sequences

    resources :documents do
      get :download, on: :member
    end

    resources :document_providers

    resources :fare_zones
    resources :fare_providers

    resources :processing_rules, as: 'processing_rule_workbenches'

    resources :calendars do
      member do
        get 'month', defaults: { format: :json }
      end
    end

    resources :imports do
      get :download, on: :member
      get :internal_download, on: :member
    end

    get 'imports/:id/import_resources/:import_resource_id/messages',
        to: 'imports#messages',
        as: 'import_import_resource_import_messages'

    resources :exports do
      get :download, on: :member
    end
  end

  resource :workbench_confirmation, only: %i[new create]

  resources :workgroups, except: [:destroy] do # rubocop:disable Metrics/BlockLength
    resources :searches, only: %i[index show create update destroy], path: ':parent_resources/searches'
    put :setup_deletion, on: :member
    put :remove_deletion, on: :member

    member do
      get :edit_aggregate
      get :edit_merge
    end

    resources :code_spaces, except: :destroy

    resources :document_types
    resources :processing_rules, as: 'processing_rule_workgroups', controller: 'workgroup_processing_rules'

    resources :workbenches, controller: :workgroup_workbenches, only: %i[new create show edit update] do
      resources :sharings, controller: 'workbench/sharings', only: %i[new create show destroy]
    end

    resource :output, controller: :workgroup_outputs
    resources :aggregates do
      member do
        put :rollback
      end
    end

    resources :publication_setups do
      resources :publications, only: [:create, :show]
    end

    resources :publication_apis do
      resources :publication_api_keys
    end

    resources :control_list_runs, controller: :workgroup_control_list_runs, only: %w[show index] do
      resources :control_runs, only: [] do

app/models/booking_arrangement.rb
class BookingArrangement < ApplicationModel
  include CodeSupport

  belongs_to :line_provider

  has_many :lines

  validates :name, presence: true
  validates :url, presence: true, url: { scheme: %w{http https} }
  validates :booking_url, presence: true, url: { scheme: %w{http https} }
  validates :minimum_booking_period, numericality: { only_integer: true, greater_than: 0, allow_nil: true }

  attribute :latest_booking_time, TimeOfDay::Type::TimeWithoutZone.new

  def latest_booking_time=(time_of_day)
    if time_of_day.is_a?(Hash)
      time_of_day = TimeOfDay.from_input_hash(time_of_day).without_utc_offset
    end

    super time_of_day
  end

  extend Enumerize

  enumerize :booking_methods, in: [:call_driver, :call_office, :online, :phone_at_stop, :text_message, :mobile_app, :at_office, :other], multiple: true
  enumerize :booking_access, in: [:public, :authorised_public, :staff, :other]
  enumerize :book_when, in: [:until_previous_day, :day_of_travel_only, :advance_and_day_of_travel, :time_of_travel_only]
  enumerize :buy_when, in: [:on_reservation, :before_boarding, :on_boarding, :after_boarding, :on_checkout]

end

app/controllers/booking_arrangements_controller.rb
# frozen_string_literal: true

class BookingArrangementsController < Chouette::LineReferentialController
  defaults resource_class: BookingArrangement

  def index
    index! do |format|
      format.html do
        @booking_arrangements = BookingArrangementDecorator.decorate(
          collection,
          context: {
            workbench: workbench
          }
        )
      end
    end
  end


  protected

  alias booking_arrangement resource


  def resource
    get_resource_ivar || set_resource_ivar(scope.find_by(id: params[:id]).decorate(context: { workbench: workbench }))
  end

  def build_resource
    get_resource_ivar || set_resource_ivar(
      end_of_association_chain.send(method_for_build, *resource_params).decorate(context: { workbench: workbench })
      )
    end

  def scope
    @scope ||= parent.booking_arrangements
  end

  def search
    @search ||= Search::BookingArrangement.from_params(params, workbench: workbench)
  end

  def collection
    @collection ||= search.search scope
  end

  private

  def booking_arrangement_params
    @booking_arrangement_params ||= params.require(:booking_arrangement).permit(
      :line_provider_id,
      :name,
      :phone,
      :url,
      :booking_access,
      :minimum_booking_period,
      :book_when,
      :latest_booking_time,
      :buy_when,
      :booking_url,
      :booking_notes,
      booking_methods: [],
      codes_attributes: %i[id code_space_id value _destroy]
    )
  end

end

app/views/booking_arrangements/_filters.html.slim
= simple_search_for @search, workbench_line_referential_booking_arrangements_path(@workbench), save_search: false do |f|
  = f.row
    = f.text

app/views/booking_arrangements/_form.html.slim
= simple_form_for([@workbench, :line_referential, @booking_arrangement],
    html: { \
      multipart: true, \
      class: 'tailwind-form', \
      id: 'booking_arrangement_form'\
    }, \
    wrapper: :horizontal_form_tailwind \
  ) do |f|
  .row
    .col-lg-12
      h2.my-16
        = t("booking_arrangements.form.sections.identification")
      = f.input :name
  .separator.section_separator
  .row
    .col-lg-12
      h2.my-16
        = t('booking_arrangements.form.sections.contact')
      = f.input :phone
      = f.input :url
  .separator.section_separator
  .row
    .col-lg-12
      h2.my-16
        = t('booking_arrangements.form.sections.rules')
      = f.input :booking_methods, as: :autocomplete_select, input_html: {class: "w-full"}
      = f.input :booking_access, as: :autocomplete_select, input_html: {class: "w-full"}
      = f.input :minimum_booking_period
      = f.input :book_when, as: :autocomplete_select, input_html: {class: "w-full"}
      = f.input :latest_booking_time, as: :time_of_day
      = f.input :buy_when, as: :autocomplete_select, input_html: {class: "w-full"}
      = f.input :booking_url
      = f.input :booking_notes, as: :text
  .separator.section_separator
  .row
    .col-lg-12
      h2.my-16
        = t('booking_arrangements.form.sections.internals')
      = f.input :line_provider_id, as: :autocomplete_select, collection: candidate_line_providers, include_blank: false, input_html: {class: "w-full"}

  .separator.section_separator

  = render 'codes/form', form: f

  = cancel_button
  = f.button :submit, t('actions.submit'), class: 'btn btn-default formSubmitr', form: 'booking_arrangement_form'

app/views/booking_arrangements/edit.html.slim
- breadcrumb :booking_arrangement, @workbench, @booking_arrangement
- page_header_content_for @booking_arrangement

.page_content
  .container-fluid
    .row
      .col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1
        = render 'form'

app/views/booking_arrangements/index.html.slim
- breadcrumb :booking_arrangements, @workbench

.page_content
  .container-fluid
    .row
      .col-lg-12
        = render 'filters'
    - if @booking_arrangements.any?
      .row
        .col-lg-12
          = table_builder_2 @booking_arrangements,
            [ \
              TableBuilderHelper::Column.new( \
                key: :uuid, \
                attribute: :uuid, \
                sortable: false, \
							), \
              TableBuilderHelper::Column.new( \
                key: :name, \
                attribute: :name, \
                link_to: -> (booking_arrangement) { workbench_line_referential_booking_arrangement_path(@workbench, booking_arrangement) } \
							), \
              TableBuilderHelper::Column.new( \
                key: :line_provider_id, \
                attribute: Proc.new { |s| s.line_provider&.name }, \
                sortable: false \
              ), \
            ].compact,
            cls: 'table has-filter has-search'

          = new_pagination @booking_arrangements, 'pull-right'

    - unless @booking_arrangements.any?
      .row.mt-xs
        .col-lg-12
          = replacement_msg t('booking_arrangements.search_no_results')

app/views/booking_arrangements/new.html.slim
- breadcrumb :new_booking_arrangement, @workbench

.page_content
  .container-fluid
    .row
      .col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-2.col-sm-10.col-sm-offset-1
        = render 'form'

app/views/booking_arrangements/show.html.slim
- breadcrumb :booking_arrangement, @workbench, @booking_arrangement
- page_header_content_for @booking_arrangement

.page_content
  .container-fluid
    .col-lg-6.col-md-6.col-sm-12.col-xs-12
      .row
        = simple_block_for @booking_arrangement, title: t('booking_arrangements.form.sections.identification') do |d|
          = d.attribute :name
          = d.attribute :phone
          = d.attribute :url, link: @booking_arrangement.url
          = d.attribute :booking_methods, as: :i18n_array, scope: [:enumerize, :booking_arrangement, :booking_methods]
          = d.attribute :booking_access, as: :enumerize
          = d.attribute :minimum_booking_period, as: :duration_in_minutes
          = d.attribute :book_when, as: :enumerize
          = d.attribute :latest_booking_time, as: :time_of_day
          = d.attribute :buy_when, as: :enumerize
          = d.attribute :booking_url, link: @booking_arrangement.booking_url
          = d.attribute :booking_notes
          = d.attribute :line_provider, as: :association, link: workbench_line_referential_line_provider_path(@workbench, @booking_arrangement.line_provider)

      .row
        = render 'codes/block', model: @booking_arrangement